# Generated by Django 3.1.2 on 2020-11-18 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lente', models.CharField(max_length=10)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='apellido')),
                ('dni', models.IntegerField(verbose_name='dni')),
                ('historial_medico', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_turno', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=10)),
                ('lejos', models.BooleanField(default=False)),
                ('cerca', models.BooleanField(default=False)),
                ('izquierda', models.BooleanField(default=False)),
                ('derecha', models.BooleanField(default=False)),
                ('armazon', models.BooleanField(default=False)),
                ('id_lente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.lente')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.turno'),
        ),
    ]
