# Generated by Django 3.1.2 on 2020-11-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='historial_medico',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
